version: "2"

services:

  mongodb:
    container_name: mongodb
    image: "mongo"
    ports: 
      - "27017:27017"
    volumes:
       - db-data:/data/db

  backend:
    container_name: node-app
    build: ./back-end/node-app/
    ports: 
      - "5004:5000"
    volumes:
      - ./back-end/node-app/:/usr/src/app
    depends_on:
      - mongodb

  frontend:
    container_name: react-app
    build: ./front-end/react-app/
    ports:
      - "9090:3000"
    volumes:
      - ./front-end/react-app/:/usr/src/app
    depends_on:
      - backend

volumes:
  db-data:
