version: "2"

services:

  backend:
    container_name: node-app
    build:
      context: ./back-end/node-app/
      dockerfile: Dockerfile
    ports: 
      - "5004:5000"
    volumes:
      - ./back-end/node-app/:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - config-server

  frontend:
    container_name: react-app
    build: 
      context: ./front-end/react-app/
      dockerfile: Dockerfile
    ports:
      - "9090:3000"
    volumes:
      - ./front-end/react-app/:/usr/src/app
    depends_on:
      - backend
  
  config-server:
    container_name: config-server
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    ports:
      - "88:8888"
    