version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    environment:
      IMAGE_NAME: jakelemar98/mern-app
      BACK_IMAGE_NAME: jakelemar98/mern-app-backend
      CONFIG_IMAGE: jakelemar90/config-server
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: cd back-end/node-app/ && npm install
      - run:
          name: Run Node.Js Tests
          command: |
            set -e
            cd back-end/node-app
            npm run test
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f ./front-end/react-app/Dockerfile-prod ./front-end/react-app/
            docker build -t $BACK_IMAGE_NAME:latest -f ./back-end/node-app/Dockerfile-prod ./back-end/node-app/
            docker build -t $CONFIG_IMAGE:latest -f ./config-server/Dockerfile ./config-server/
      - run:
          name: Push Docker Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            docker tag $BACK_IMAGE_NAME:latest $BACK_IMAGE_NAME:$CIRCLE_SHA1
            docker push $BACK_IMAGE_NAME:latest
            docker push $BACK_IMAGE_NAME:$CIRCLE_SHA1
            docker tag $CONFIG_IMAGE:latest $CONFIG_IMAGE:$CIRCLE_SHA1
            docker push $CONFIG_IMAGE:latest
            docker push $CONFIG_IMAGE:$CIRCLE_SHA1
      - run:
          name: PR Check
          command: |
            if [[ $(echo "$CIRCLE_BRANCH" | grep -c "master") -gt 0 ]]; then
              echo "Skip doing stuff since it is a PR." && echo "$CIRCLE_BRANCH"
              sudo apt-get update && sudo apt-get -y install gettext-base
              curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
              chmod u+x ./kubectl
              ./scripts/ci-deploy.sh
            else
              echo "Not a PR, so now do what I want." && echo "$CIRCLE_BRANCH"
            fi
      - slack/notify:
          color: '#42e2f4'
          message: A build has just completed! Production URL => app.jalema01-mern-app.com
          webhook: $SLACK_HOOK
orbs:
  slack: circleci/slack@3.3.0

