version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    environment:
      IMAGE_NAME: jakelemar98/mern-app
      BACK_IMAGE_NAME: jakelemar98/mern-app-backend
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: cd back-end/node-app/ && npm install
      - run:
          name: Run Node.Js Tests
          command: |
            set -e
            cd back-end/node-app && npm run test
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f ./front-end/react-app/Dockerfile-prod ./front-end/react-app/
      - run:
          name: Push Docker Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Build Docker image
          command: |
            docker build -t $BACK_IMAGE_NAME:latest -f ./back-end/node-app/Dockerfile-prod ./back-end/node-app/
      - run:
          name: Push Docker Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            docker tag $BACK_IMAGE_NAME:latest $BACK_IMAGE_NAME:$CIRCLE_SHA1
            docker push $BACK_IMAGE_NAME:latest
            docker push $BACK_IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
