apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mern-app
  namespace: default
  labels:
    app: k8s-mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mern-app
  template:
    metadata:
      labels:
        app: k8s-mern-app
    spec:
      containers:
        - name: k8s-mern-app
          image: jakelemar98/mern-app:$COMMIT_SHA1
          ports:
            - containerPort: 9376
              name: http
