apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mern-ingress
spec:
  rules:
  - http:
      paths:
      - path: /mern-app
        backend:
          serviceName: k8s-mern-service
          servicePort: 8080
      