apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mern-ingress
spec:
  rules:
  - host: app.jalema01-mern-app.com
    http:
      paths:
      - backend:
          serviceName: mern-app
          servicePort: 8080
  - host: backend.jalema01-mern-app.com
    http:
      paths:
      - backend:
          serviceName: mern-app-back
          servicePort: 8080
      