apiVersion: v1
kind: Service
metadata:
  name: k8s-mern-app
  namespace: default
  labels:
    app: k8s-mern-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: k8s-mern-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http