server:
  port: 8888
spring:
  application:
    name: node-backend
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jakelemar98/appConfig
          search-paths:
          - '{application}'
