server:
  port: 8888
spring:
  application:
    name: node-backend
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jakelemar98/appConfig
          username: jakelemar98
          password: Isu02201998
          clone-on-start: true
          search-paths:
          - '{application}'
